# Generated by Django 3.2.19 on 2023-08-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
