# Generated by Django 3.2.19 on 2023-08-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngict', '0003_auto_20230810_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
