# Generated by Django 3.2.19 on 2023-08-25 17:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngict', '0005_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
