# Generated by Django 3.2.19 on 2023-08-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngict', '0005_alter_assessment_course_alter_lesson_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
