# Generated by Django 3.2.19 on 2023-08-26 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ngict', '0006_note_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='username',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
