# Generated by Django 3.2.19 on 2023-08-27 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngict', '0007_auto_20230826_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
