# Generated by Django 3.2.19 on 2023-08-15 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ngict', '0008_auto_20230815_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='username',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
