# Generated by Django 3.2.19 on 2023-09-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        ('ngict', '0008_remove_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='module',
        ),
        migrations.RemoveField(
            model_name='assessmentscore',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentscore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='project',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='submitted_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instructors.project'),
        ),
        migrations.AlterField(
            model_name='student',
            name='assessment_scores',
            field=models.ManyToManyField(blank=True, related_name='students', to='instructors.AssessmentScore'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(to='instructors.Course'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.course'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='AssessmentScore',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
