# Generated by Django 3.2.19 on 2023-09-04 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_auto_20230904_0124'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ngict', '0009_auto_20230901_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='submitted_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instructors.project'),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
