# Generated by Django 3.2.19 on 2023-09-29 20:17

from django.db import migrations, models
import django.utils.timezone
import ngict.models


class Migration(migrations.Migration):

    dependencies = [
        ('ngict', '0010_auto_20230904_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=ngict.models.generate_upload_path)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
