# Generated by Django 3.2.19 on 2023-09-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngict', '0011_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created_at',
        ),
    ]
