# Generated by Django 3.2.19 on 2023-10-02 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0014_course_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ngict', '0012_remove_image_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.lesson'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.module'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'course', 'module', 'lesson')},
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='week',
        ),
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
