# Generated by Django 3.2.19 on 2023-10-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0015_assessment_is_taken'),
        ('ngict', '0013_auto_20231002_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='assessments_completed',
            field=models.ManyToManyField(blank=True, to='instructors.Assessment'),
        ),
    ]
