# Generated by Django 3.2.19 on 2023-09-05 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_auto_20230905_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='instructors.course'),
            preserve_default=False,
        ),
    ]
