# Generated by Django 3.2.19 on 2023-09-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0007_lesson_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='order',
            new_name='id',
        ),
    ]
