# Generated by Django 3.2.19 on 2023-09-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0009_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
