# Generated by Django 3.2.19 on 2023-09-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0012_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategories',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
