# Generated by Django 3.2.19 on 2023-09-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0013_alter_coursecategories_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='images/course_images/'),
            preserve_default=False,
        ),
    ]
