# Generated by Django 3.2.19 on 2023-10-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0014_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
